### ISSUE TITLE
Magic numbers

### ISSUE THREAD

**Issue by Irama03** [YouGin501/EuroDiffusion#1]
It's recommended to avoid magic values in the code. You might want to create a constant, for example: BOARD_SIZE = 19.
https://github.com/YouGin501/EuroDiffusion/blob/87865dba6ced8dcbc1d49cac783e6d09e260545a/ConsoleApp1/Program.cs#L24

**Comment by YouGin501** [comment]
Thank you for your comment. Issue fixed
