### ISSUE TITLE
Early return

### ISSUE THREAD

**Issue by IanaKhitsko** [YouGin501/EuroDiffusion#2]
https://github.com/YouGin501/EuroDiffusion/blob/1f1e12bbbccf1653d899fe1632f0021f6efa6e7a/ConsoleApp1/Program.cs#L67

it would be better to return earlier to reduce code blocks numbers

**Comment by YouGin501** [comment]
Thank you for your comment. I added "continue" to skip the iteration that doesn't match this requirement.
