### ISSUE TITLE
input data check

### ISSUE THREAD

**Issue by IanaKhitsko** [YouGin501/EuroDiffusion#3]
https://github.com/YouGin501/EuroDiffusion/blob/1f1e12bbbccf1653d899fe1632f0021f6efa6e7a/ConsoleApp1/Program.cs#L98

So if I'll have 10 empty lines and 30 non-empty lines in input.txt - the validation is ok?

**Comment by YouGin501** [comment]
Well, this is the first check inside the validation method. Further checks won't be necessary if the input data doesn't match this requirement. So the answer is no, the validation is not ok
